#!/bin/bash
# Weekly Metrics Report Generator
# Genera reporte semanal de métricas del proyecto

set -e

REPORT_DATE=$(date '+%Y-%m-%d')
REPORT_FILE="reports/weekly-metrics-${REPORT_DATE}.md"

echo "📊 Generating Weekly Metrics Report"
echo "Date: $REPORT_DATE"
echo ""

# Crear directorio de reports si no existe
mkdir -p reports

# Activar venv si existe
if [ -d ".venv" ]; then
    source .venv/bin/activate
fi

# Iniciar reporte
cat > "$REPORT_FILE" << EOF
# Weekly Metrics Report

**Date:** $REPORT_DATE  
**Generated by:** GitHub Actions / Manual

---

## Test Coverage

EOF

# Obtener coverage si pytest está disponible
if command -v pytest &> /dev/null; then
    echo "## Test Coverage" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    pytest --cov=src --cov-report=term-missing --quiet 2>/dev/null | tail -5 >> "$REPORT_FILE" || echo "Coverage data unavailable" >> "$REPORT_FILE"
else
    echo "pytest not available" >> "$REPORT_FILE"
fi

cat >> "$REPORT_FILE" << EOF

---

## GitHub Issues Metrics

EOF

# Obtener métricas de GitHub si gh CLI está disponible
if command -v gh &> /dev/null; then
    echo "Fetching GitHub metrics..."
    
    TOTAL_ISSUES=$(gh issue list --json number --jq 'length' 2>/dev/null || echo "0")
    OPEN_ISSUES=$(gh issue list --state open --json number --jq 'length' 2>/dev/null || echo "0")
    CLOSED_ISSUES=$(gh issue list --state closed --json number --jq 'length' 2>/dev/null || echo "0")
    
    cat >> "$REPORT_FILE" << EOF
- **Total Issues:** $TOTAL_ISSUES
- **Open Issues:** $OPEN_ISSUES
- **Closed Issues:** $CLOSED_ISSUES
- **Completion Rate:** $(echo "scale=1; $CLOSED_ISSUES * 100 / ($TOTAL_ISSUES + 1)" | bc)%

EOF
else
    echo "gh CLI not available" >> "$REPORT_FILE"
fi

cat >> "$REPORT_FILE" << EOF

---

## Code Statistics

EOF

# Contar líneas de código
if command -v cloc &> /dev/null; then
    cloc src/ --quiet >> "$REPORT_FILE" 2>/dev/null || echo "cloc not available" >> "$REPORT_FILE"
else
    echo "Counting Python files..." >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    find src/ -name "*.py" | wc -l | xargs echo "Python files:" >> "$REPORT_FILE"
    find src/ -name "*.py" -exec wc -l {} + | tail -1 | awk '{print "Total lines: " $1}' >> "$REPORT_FILE"
fi

cat >> "$REPORT_FILE" << EOF

---

## Data Quality (if database available)

EOF

if [ -n "$DATABASE_URL" ]; then
    python3 scripts/monitoring/check_data_freshness.py \
        --database-url "$DATABASE_URL" \
        --threshold-days 7 >> "$REPORT_FILE" 2>&1 || echo "Data quality check unavailable" >> "$REPORT_FILE"
else
    echo "DATABASE_URL not set" >> "$REPORT_FILE"
fi

cat >> "$REPORT_FILE" << EOF

---

**Report generated:** $(date '+%Y-%m-%d %H:%M:%S')
EOF

echo "✅ Report generated: $REPORT_FILE"
cat "$REPORT_FILE"

