name:  Bug Report
description: Reportar un error o comportamiento incorrecto
title: "[Bug]: "
labels: ["bug", "priority-medium"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por reportar un bug. Por favor completa la informaci贸n para ayudarnos a resolverlo.

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n del Bug
      description: Describe claramente qu茅 est谩 fallando
      placeholder: La funci贸n X falla cuando...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Pasos para Reproducir
      description: Lista los pasos para reproducir el error
      placeholder: |
        1. Ejecutar comando X
        2. Ver error Y
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamiento Esperado
      description: Qu茅 deber铆a ocurrir
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamiento Actual
      description: Qu茅 ocurre realmente
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs de Error
      description: Copia aqu铆 los logs relevantes
      render: shell

  - type: input
    id: files
    attributes:
      label: Archivos Afectados
      description: Rutas de archivos relacionados
      placeholder: src/etl/pipeline.py:156

  - type: dropdown
    id: priority
    attributes:
      label: Prioridad
      options:
        - " High - Bloquea desarrollo"
        - " Medium - Importante pero no urgente"
        - " Low - Nice to have"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Entorno
      description: Informaci贸n del sistema
      value: |
        - OS: [ej: Ubuntu 22.04]
        - Python: [ej: 3.11.5]
        - Versi贸n del proyecto: [ej: commit SHA]

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: He buscado si ya existe un issue similar
          required: true
        - label: He incluido informaci贸n suficiente para reproducir el bug
          required: true

