name:  Epic - Feature Implementation
description: Template para implementaci贸n de features del roadmap
title: "[FEATURE-XX] "
labels: ["enhancement", "epic"]
assignees:
  - prototyp33
body:
  - type: markdown
    attributes:
      value: |
        ##  Feature del Roadmap
        Este template es para las 8 features priorizadas del an谩lisis comparativo.

  - type: input
    id: feature_id
    attributes:
      label: Feature ID
      description: N煤mero de la feature del an谩lisis comparativo
      placeholder: "#XX"
    validations:
      required: true

  - type: dropdown
    id: sprint
    attributes:
      label: Sprint Asignado
      description: En qu茅 sprint se desarrollar谩 esta feature
      options:
        - "Sprint 1 (Semanas 1-4) - Quick Wins"
        - "Sprint 2 (Semanas 5-10) - Core ML"
        - "Sprint 3 (Semanas 11-18) - Data Expansion"
        - "Sprint 4 (Semanas 19-24) - Showcase"
    validations:
      required: true

  - type: input
    id: effort
    attributes:
      label: Esfuerzo Estimado
      description: Horas estimadas para completar
      placeholder: "15-20 horas"
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencias
      description: Issues o features que deben completarse antes
      placeholder: |
        - #XX (descripci贸n)
        - Datos de XXX disponibles
        - API de XXX configurada

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n y Valor de Negocio
      description: Qu茅 problema resuelve y por qu茅 es importante
    validations:
      required: true

  - type: textarea
    id: components
    attributes:
      label: Componentes T茅cnicos
      description: Archivos y m贸dulos a crear/modificar
      value: |
        - [ ] `src/analytics/nuevo_modulo.py` - [Descripci贸n]
        - [ ] `src/app/pages/nueva_pagina.py` - [Descripci贸n]
        - [ ] `tests/test_nuevo_modulo.py` - [Descripci贸n]
        - [ ] Actualizar `requirements.txt` con: [librer铆as]
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Criterios de Aceptaci贸n
      description: Qu茅 debe cumplirse para considerar la feature completa
      value: |
        - [ ] Funcionalidad core implementada y probada
        - [ ] Tests unitarios con >80% cobertura
        - [ ] Documentaci贸n en `docs/features/feature-XX.md`
        - [ ] UI integrada en dashboard Streamlit
        - [ ] Datos persistidos en SQLite (si aplica)
    validations:
      required: true

  - type: textarea
    id: testing_plan
    attributes:
      label: Plan de Testing
      description: C贸mo se validar谩 la implementaci贸n
      value: |
        - [ ] Tests unitarios en `tests/`
        - [ ] Test manual con datos reales de Barcelona
        - [ ] Validaci贸n visual en Streamlit local
        - [ ] Performance check (<3s carga p谩gina)

  - type: textarea
    id: metrics
    attributes:
      label: M茅tricas de xito
      description: KPIs y valores objetivo
      placeholder: |
        - KPI: Tiempo de respuesta dashboard
        - Target: <2 segundos
        - KPI: Accuracy del modelo
        - Target: >85%

  - type: textarea
    id: subtasks
    attributes:
      label: Sub-tareas
      description: Desglose en tareas m谩s peque帽as (usar template sub-issue)
      placeholder: |
        - [ ] #XXX - Implementar l贸gica de c谩lculo
        - [ ] #XXX - Crear UI Streamlit
        - [ ] #XXX - A帽adir tests unitarios
        - [ ] #XXX - Documentaci贸n

  - type: textarea
    id: references
    attributes:
      label: Referencias
      description: Enlaces a documentos, APIs, o issues relacionados
      placeholder: |
        - [Documento de an谩lisis](docs/...)
        - [API Docs](https://...)
        - Issues relacionados: #X, #Y

  - type: textarea
    id: risks
    attributes:
      label: Riesgos y Mitigaciones
      description: Posibles problemas y c贸mo abordarlos
      placeholder: |
        - **Riesgo:** API externa con rate limits
          **Mitigaci贸n:** Implementar caching y retry logic
        - **Riesgo:** Performance con datasets grandes
          **Mitigaci贸n:** Lazy loading y paginaci贸n

